modLoader = "javafml"
loaderVersion = "[1,)" # NeoForge loader version range
license = "MIT"

[[mods]]
modId = "questinstaller"
version = "1.0.0"
displayName = "Quest Installer"
description = '''
Copies default quest and texture files into config and kubejs folders if missing.
'''

[[dependencies.questinstaller]]
modId = "minecolonies"
mandatory = false
versionRange = "[1.1.1041-1.21.1,)"
side = "BOTH"

[[dependencies.questinstaller]]
modId = "ftbquests"
mandatory = false
versionRange = "[2001.4.14,)"
side = "BOTH"